// <auto-generated />
using System;
using ManpreetBookStore.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ManpreetBooks.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231120181657_AddCoverTypeToDb")]
    partial class AddCoverTypeToDb : AddCoverTypeToDbBase
    {
    }

    internal class AddCoverTypeToDbBase
    {
    }
}
